### ISSUE TITLE
Java error when loading Burp Extension

### ISSUE THREAD

**Issue by jaconll12** [NetSPI/burp-plugins#2]
When loading the .jar file I get the error
ava.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.k1d.a(Unknown Source)
	at burp.k1d.<init>(Unknown Source)
	at burp.llg.a(Unknown Source)
	at burp.lub.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

please advise on the issue

**Comment by JacobReynolds** [comment]
Which burp extension was this for?

**Comment by jaconll12** [comment]
BurpAMFDSer



Jimmy Lloyd

**Comment by JacobReynolds** [comment]
Hey Jimmy,

Confirming I'm seeing the same issue.  I'm assuming the jar wasn't compiled with the BurpExtender classes included.  I'll work on getting a new jar up, and will post here once it's working.

Thanks for pointing that out.
--Jake

**Comment by KenDJohnson** [comment]
I have recompiled the jar and updated the Burp interface files. It is now loading properly for me on the newest version of Burp in both Windows and Linux. Please let me know if you are still unable to load the extension.

**Comment by jaconll12** [comment]
Works perfectly now.  Thank you.  In doing some research I was thinking it was a compile issue, but I didn't want to extract and recompile your code without checking with you first. But thank you so much 👍

**Comment by KenDJohnson** [comment]
Yeah absolutely. I'm still not entirely sure what the issue was, it was working in my main Linux build, but not Windows. Looks good now though so I'll close up the issue.

**Comment by Jamiewjchen** [comment]
i have the same issue for my Burp in newest version  on Macbook as
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at burp.ff4.a(Unknown Source)
	at burp.ff4.<init>(Unknown Source)
	at burp.bg9.a(Unknown Source)
	at burp.eug.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	@KenDJohnson

**Comment by qing-root** [comment]
i have the same issue,java version is java17,burp version is 2023.10.6

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: GUI/OptionsPanel
	at burp.Zfl4.ZN(Unknown Source)
	at burp.Zmwn.Zm(Unknown Source)
	at burp.Ziox.ZO(Unknown Source)
	at burp.Zcg7.addSuiteTab(Unknown Source)
	at burp.Zfz4.addSuiteTab(Unknown Source)
	at burp.Zs7y.addSuiteTab(Unknown Source)
	at burp.Zyn_.addSuiteTab(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:477)
	at org.python.core.PyObject.__call__(PyObject.java:481)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx4.registerExtenderCallbacks$3(C:/Tools/00.Burp/BurpSuite_plugns/Burp_Auxiliary/Nuclei-BurpExtension-main/nuclei-extension.py:55)
	at org.python.pycode._pyx4.call_function(C:/Tools/00.Burp/BurpSuite_plugns/Burp_Auxiliary/Nuclei-BurpExtension-main/nuclei-extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$2.registerExtenderCallbacks(Unknown Source)
	at burp.Zsm2.ZS(Unknown Source)
	at burp.Zsmz.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.RuntimeException: java.lang.NoClassDefFoundError: GUI/OptionsPanel
	at burp.Zfl4.ZN(Unknown Source)
	at burp.Zmwn.Zm(Unknown Source)
	at burp.Ziox.ZO(Unknown Source)
	at burp.Zcg7.addSuiteTab(Unknown Source)
	at burp.Zfz4.addSuiteTab(Unknown Source)
	at burp.Zs7y.addSuiteTab(Unknown Source)
	at burp.Zyn_.addSuiteTab(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:477)
	at org.python.core.PyObject.__call__(PyObject.java:481)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx4.registerExtenderCallbacks$3(C:/Tools/00.Burp/BurpSuite_plugns/Burp_Auxiliary/Nuclei-BurpExtension-main/nuclei-extension.py:55)
	at org.python.pycode._pyx4.call_function(C:/Tools/00.Burp/BurpSuite_plugns/Burp_Auxiliary/Nuclei-BurpExtension-main/nuclei-extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$2.registerExtenderCallbacks(Unknown Source)
	at burp.Zsm2.ZS(Unknown Source)
	at burp.Zsmz.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://github.com/NetSPI/Burp-Extensions/assets/30001685/05d9ea6d-8d43-4f1c-b463-3693c8cdf008)
